#include <windows.h>
#include <tlhelp32.h>


DECLSPEC_IMPORT HANDLE  WINAPI KERNEL32$CreateToolhelp32Snapshot(DWORD dwFlags, DWORD th32ProcessID);
DECLSPEC_IMPORT BOOL    WINAPI KERNEL32$Process32FirstW(HANDLE hSnapshot, LPPROCESSENTRY32W lppe);
DECLSPEC_IMPORT BOOL    WINAPI KERNEL32$Process32NextW(HANDLE hSnapshot, LPPROCESSENTRY32W lppe);
DECLSPEC_IMPORT DWORD   WINAPI KERNEL32$GetLastError();
DECLSPEC_IMPORT BOOL    WINAPI KERNEL32$CloseHandle(HANDLE hObject);
DECLSPEC_IMPORT DWORD   WINAPI KERNEL32$WaitForSingleObjectEx(HANDLE, DWORD, BOOLEAN);
DECLSPEC_IMPORT DWORD   WINAPI KERNEL32$GetTickCount(); 

DECLSPEC_IMPORT DWORD   WINAPI USER32$MsgWaitForMultipleObjects(DWORD, CONST HANDLE*, BOOL, DWORD, DWORD);
DECLSPEC_IMPORT BOOL    WINAPI USER32$EnumWindows(WNDENUMPROC, LPARAM);
DECLSPEC_IMPORT BOOL    WINAPI USER32$IsWindowVisible(HWND);
DECLSPEC_IMPORT HWND    WINAPI USER32$GetForegroundWindow(void);
DECLSPEC_IMPORT DWORD   WINAPI USER32$GetWindowThreadProcessId(HWND, LPDWORD);
DECLSPEC_IMPORT int     WINAPI USER32$GetWindowTextA(HWND, LPSTR, int);
DECLSPEC_IMPORT BOOL    WINAPI USER32$PeekMessageA(LPMSG, HWND, UINT, UINT, UINT);
DECLSPEC_IMPORT LRESULT WINAPI USER32$DispatchMessageA(const MSG*);
DECLSPEC_IMPORT HHOOK   WINAPI USER32$SetWindowsHookExA(int idHook, HOOKPROC lpfn, HINSTANCE hmod, DWORD dwThreadId);
DECLSPEC_IMPORT BOOL    WINAPI USER32$UnhookWindowsHookEx(HHOOK hhk); 
DECLSPEC_IMPORT SHORT   WINAPI USER32$GetAsyncKeyState(int);
DECLSPEC_IMPORT SHORT   WINAPI USER32$GetKeyState(int);
DECLSPEC_IMPORT int     WINAPI USER32$ToUnicode(UINT, UINT, const BYTE*, LPWSTR, int, UINT);
DECLSPEC_IMPORT LRESULT WINAPI USER32$CallNextHookEx(HHOOK, int, WPARAM, LPARAM);

DECLSPEC_IMPORT int     WINAPI MSVCRT$towlower(int);
DECLSPEC_IMPORT int     WINAPI MSVCRT$wcscmp(const WCHAR*, const WCHAR*);
DECLSPEC_IMPORT size_t  WINAPI MSVCRT$wcslen(const WCHAR*);
DECLSPEC_IMPORT char*   WINAPI MSVCRT$strstr(const char*, const char*);
DECLSPEC_IMPORT char*   WINAPI MSVCRT$strncpy(char*, const char*, size_t);
DECLSPEC_IMPORT void*   WINAPI MSVCRT$memcpy(void*, const void*, size_t);
DECLSPEC_IMPORT void*   WINAPI MSVCRT$memset(void*, int, size_t);
DECLSPEC_IMPORT size_t  WINAPI MSVCRT$strlen(const char*);

typedef struct {
    DWORD dwPid;
    HWND  hWnd;
    char  title[256]; 
} ENUM_PARAM, *PENUM_PARAM;

#define KEY_BUFFER_SIZE 4096